export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const REQUEST_RESTART = 'REQUEST_RESTART';
export const CHOOSE_DIFFICULTY = 'CHOOSE_DIFFICULTY';
export const CHOOSE_CATEGORY = 'CHOOSE_CATEGORY';
